#!/bin/bash

# $Id$

# Run this script at your own risk

rm    -Rf /tmp/dcf_plastex/html /tmp/dcf_plastex/xml
mkdir -p  /tmp/dcf_plastex/html /tmp/dcf_plastex/xml

cp -r /home/dcf21/pyxplot/pyxplot9/doc/*.tex /tmp/dcf_plastex/xml
cp /home/dcf21/pyxplot/extras/plastex/XMLhelp/* /tmp/dcf_plastex/xml

cd /tmp/dcf_plastex/xml

./plastex.manual pyxplot.gp_help.tex

cp gp_help.xml /home/dcf21/pyxplot/pyxplot9/src/help.xml
